plugins {
    id 'net.neoforged.moddev' version '2.0.28-beta'
    id 'java'
    id 'maven-publish'
}

file('build.properties').withReader {
    def prop = new Properties()
    prop.load(it)
    project.ext.config = new ConfigSlurper().parse prop
}

version = "${config.mc_version}-${config.mod_version}"
group = "com.brandon3055.projectintelligence"
archivesBaseName = "ProjectIntelligence"

println "Starting build of ${archivesBaseName}, Version: ${config.mod_version}"
println "Using NeoForge: ${config.neoforge_version}, for Minecraft: ${config.mc_version}"

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = config.neoforge_version

    runs {
        client {
            client()
        }
        server {
            server()
        }
        data {
            data()
            programArguments.addAll '--mod', 'projectintelligence', '--all', '--output', file("src/generated/resources").getAbsolutePath(), '--existing', file("src/main/resources").getAbsolutePath()
        }
    }

    mods {
        projectintelligence {
            source sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDirs += "src/generated/resources"

repositories {
    mavenLocal()
    maven { url = "https://maven.covers1624.net/" }
    maven {
        name = "Progwml6 maven"
        url = "https://dvs1.progwml6.com/files/maven"
    }
    maven {
        name = "tterrag maven"
        url = "https://maven.tterrag.com/"
    }
}

dependencies {
    implementation "net.neoforged:neoforge:${config.neoforge_version}"
    implementation fg.deobf("com.brandon3055.brandonscore:BrandonsCore:${config.mc_version}-${config.bcore_version}")
    implementation fg.deobf("codechicken:CodeChickenLib:${config.mc_version}-${config.ccl_version}")
    implementation fg.deobf("mezz.jei:jei-${config.mc_version}:${config.jei_version}:api")
    runtimeOnly fg.deobf("mezz.jei:jei-${config.mc_version}:${config.jei_version}")
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

processResources {
    inputs.property 'version', project.version

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand 'version': project.version,
               'mc_version': config.mc_version,
               'neoforge_version': config.neoforge_version,
               'ccl_version': "[${config.ccl_version.replace('.+', '')},${config.ccl_version_max})",
               'bcore_version': "[${config.bcore_version.replace('.+', '')},)"
    }
}

jar {
    from(file("LICENSE"))
    manifest {
        attributes 'Specification-Title': archivesBaseName
        attributes 'Specification-Vendor': 'brandon3055'
        attributes 'Specification-Version': "1"
        attributes 'Implementation-Title': archivesBaseName
        attributes 'Implementation-Vendor': 'brandon3055'
        attributes 'Implementation-Version': project.version
        attributes 'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
    }
}

task srcJar(type: Jar) {
    dependsOn classes
    from sourceSets.main.allSource
    archiveClassifier = 'sources'
    from file("LICENSE")
}

task deobfJar(type: Jar) {
    dependsOn classes
    from sourceSets.main.output
    archiveClassifier = 'deobf'
    from file("LICENSE")
}

artifacts {
    archives jar
    archives srcJar
    archives deobfJar
}
